<?php
///////////////////////////////////////////////////////////////////////
/// LITTLE-NET WEB TOOL : BasicAuth 1.7
/// http://l-tool.net/
/// http://little-net.jp/
/// Copyright (C) Akira Mori. All rights reserved.
/// 2008-03-15 : created
/// 2013-09-09 : modified
/// [UTF-8]
///////////////////////////////////////////////////////////////////////
$LLMSG_STR = array('inchk0001'		=> '$p1 を指定して下さい。','inchk0001-en'	=> 'Please enter the "$p1".','inchk0002'		=> '$p1 と $p2 が違っています。','inchk0002-en'	=> '"$p1" and "$p2" is incorrect.','inchk0003'		=> '$p1 と $p2 のどちらかは指定して下さい。','inchk0003-en'	=> 'Please enter "$p1" or "$p2" either.','chk2exist01'	=> '$p1 を指定して下さい。','chk2exist01-en'=> 'Please enter the "$p1".','chk2len01'		=> '$p1 は $p2 ～ $p3 字で指定して下さい。','chk2len02'		=> '$p1 は $p2 字以内で指定して下さい。','chk2len03'		=> '$p1 は $p2 字以上で指定して下さい。','chk2roma01'	=> '－年','chk2roma01-en'	=> '(year)','chk2roma02'	=> '$p1 は半角文字で指定して下さい。','chk2roma02-en'	=> 'Please enter the "$p1" in English.','chk2roma03'	=> '$p1 は数値で指定して下さい。','chk2roma03-en'	=> 'Please enter the "$p1" at numeric.','chk2roma04'	=> '$p1 は $p2 以上を指定して下さい。','chk2roma04-en'	=> 'Please enter the "$p1" of $p2 or more.','chk2roma05'	=> '$p1 は $p2 以下を指定して下さい。','chk2roma05-en'	=> 'Please enter the "$p1" of "$p2" or less.','chk2roma06'	=> '$p1 は $p2 ～ $p3 を指定して下さい。','chk2roma06-en'	=> 'Please enter the "$p1" between $p2 to $p3.','chk2roma07'	=> '$p1 を正しい形式（例：03-0000-0000 ）で指定して下さい。','chk2roma07-en'	=> 'Please enter the "$p1" at the right format.','chk2roma08'	=> '$p1 を正しい形式（例：1230123、ハイフン無し７桁）で指定して下さい。','chk2roma08-en'	=> 'Please enter the "$p1" at the right format.','chk2roma09'	=> '$p1 を正しい形式（例：info@sample.com ）で指定して下さい。','chk2roma09-en'	=> 'Please enter the "$p1" at the right format.  (e.g. info@sample.com)','chk2roma10'	=> '$p1 を正しい形式（例：http://www.sample.com/ ）で指定して下さい。',

'chk2roma10-en'	=> 'Please enter the "$p1" at the right format.  (e.g. http://www.sample.com/)',

'chk2roma11'	=> '$p1 は $2 ～ $3 文字の半角英数字で指定して下さい。','chk2roma11-en'	=> 'Please enter the "$p1" at length betwenn $p2 to $p3 characters.','chk2roma12'	=> '$p1 が正しい日付で指定されていません。','chk2roma12-en'	=> 'Please enter the "$p1" at the right date.','chk2roma13'	=> '$p1 を正しい日付（ yyyy-mm-dd ）で指定して下さい。','chk2roma13-en'	=> 'Please enter the "$p1" at the right date.  (e.g. 2000-01-31)','chk2roma14'	=> '$p1 を正しい日付（ yyyy-mm-dd 又は yyyy-mm-dd hh:mi:ss ）で指定して下さい。','chk2roma14-en'	=> 'Please enter the "$p1" at the right date.  (e.g. 2000-01-31 or 2000-01-31 23:59:59)','chk2code01'	=> '$p1 が正しい項目数で指定されていません。','chk2code02'	=> '$p1 のコードが正しい形式で指定されていません。','imgupload01'	=> 'この形式のファイルはアップロード出来ません。','imgupload01-en'=> 'Can not upload this type file.','imgupload02'	=> 'ファイルサイズが大きすぎます。最大サイズは $p1 Kbyte 以内です。','imgupload02-en'=> 'File size is too large to upload. Maximum size is $p1 Kbyte.','imgupload03'	=> 'ファイルをアップロードできませんでした。','imgupload03-en'=> 'Can not upload the file.','imgupload04'	=> 'ファイルは未登録です','imgupload04-en'=> 'No file','formset01'		=> '設定しました。','formset02'		=> '設定できませんでした。','updatemode01'	=> 'サンプルサイトのため変更できません。','limit01'		=> 'この機能を利用するにはソフトウェア制限の解除申請を行って下さい。','limit02'		=> '$p1 件以上登録するにはソフトウェア制限の解除申請を行って下さい。','setupload01'	=> '設定情報をアップロードしました。','setupload02'	=> 'アップロードするファイルを指定して下さい。','setupload03'	=> 'この設定情報はアップロードできません。','setupload04'	=> '新しいバージョンの設定情報はアップロードできません。','setupload05'	=> '設定情報をアップロードできませんでした。','setupload06'	=> '現在の設定情報が残っているためアップロードできませんでした。',);
?>